name: sync-code
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  watch:
    types: started

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential git git-core curl wget jq
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        
    - name: Get Code from Private Repository
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts
        git clone -b main git@github.com:42wim/edgeupdates.git main
        
    - name: Push to main
      run: |
        echo -e "${{ secrets.GITHUBKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts
        cd main
        git remote add github "${{ secrets.GITHUBREPO }}"
        git push -u github main >/dev/null 2>&1
        
    - name: Get Code from Private Repository
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts
        git clone -b gh-pages git@github.com:42wim/edgeupdates.git gh-pages
        
    - name: Push to gh-pages
      run: |
        echo -e "${{ secrets.GITHUBKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts
        cd gh-pages
        git remote add github "${{ secrets.GITHUBREPO }}"
        git push -u github gh-pages >/dev/null 2>&1
        
    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 0